[package]
name = "sces-os"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0"
authors = ["Khose-ie<khose-ie@outlook.com>"]
description = "Simple Construction of Embedded Software - OS Definitions"

[lib]
name = "sces_os"
test = false
bench = false

[dependencies]
sces = "0.1.0"

[features]
