[package]
name = "sces-svc"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0"
authors = ["Khose-ie<khose-ie@outlook.com>"]
description = "Simple Construction of Embedded Software - Service."

[lib]
name = "sces_svc"
test = false
bench = false

[dependencies]
sces = "0.1.0"
log = "0.4"
