[package]
name = "sces"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0"
authors = ["Khose-ie<khose-ie@outlook.com>"]
description = "Simple Construction of Embedded Software - Common Definitions"

[lib]
name = "sces"
test = false
bench = false

[dependencies]

[features]
